name: ExampleProject
platforms:
  ios:
    minimum: "16.0"
  macos:
    minimum: "14.0"
deploymentTarget: "14.0"
targets:
  App:
    type: application
    deploymentTarget: "14.0"
  AppTest:
    type: test
    deploymentTarget: "14.0"
  Library:
    type: library
    deploymentTarget: "14.0"
  LibraryTest:
    type: test
    deploymentTarget: "14.0"
  Helper:
    type: helper
